name: demo1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide branch name'
        required: true
        default: main
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    steps: 
    - name: Build sample app
      id: get_status
      run: |
        echo "backend_status=failed" >> "$GITHUB_OUTPUT"
        echo "frontend_status=failed" >> "$GITHUB_OUTPUT"
    outputs:
      bk_status: ${{ steps.get_status.outputs.backend_status }}
      ft_status: ${{ steps.get_status.outputs.frontend_status }}
      
      
  test1:
    if: ${{ github.actor == 'gniadzix' }} && ${{ needs.demo.outputs.bk_status == 'success' || needs.demo.outputs.ft_status == 'success' }}
    needs: demo
    runs-on: ubuntu-latest
    steps: 
    - name: echo success
      run: echo "succees"
      
