name: demo1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide branch name'
        required: true
        default: main
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    steps: 
    - name: Build sample app
      id: get_status
      run: |
        test1=success
        test2=success
        if [ "$test1" == "failed" ] || [ "$test2" == "failed" ]; then
          exit 1
        else
          exit 0
        fi
      
      
  test1:
    needs: demo
    runs-on: ubuntu-latest
    steps: 
    - name: echo success
      run: echo "succees"
      
