name: demo2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide branch name'
        required: true
        default: main
        type: string
  pull_request:
    branches: [ "main" ]

jobs:
  demo:
    environment: demo_env
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Build sample app
      run: |
        jar -cvf sampleapp.war *
      
    - name: Deploy app
      uses: gniadzix/devops-demo/.github/workflows/deploy.yml@main
      with:
        tomcat_path: ${{secrets.TOMCAT_PATH_ENV}}
