name: demo2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide branch name'
        required: true
        default: main
        type: string
      env_name:
        description: 'Provide env name'
        required: true
        default: demo_env
        type: string
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Build sample app
      run: |
        jar -cvf sampleapp.war *
        
  deploy:
    uses: gniadzix/devops-demo/.github/workflows/deploy.yml@main
    with:
      env_name: ${{ github.event.inputs.env_name }}
    secrets: inherit
