name: demo1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build sample app
      run: |
        jar -cvf sampleapp.war *
      
    - name: Deploy app
      run: |
        if (Test-Path ${{secrets.TOMCAT_PATH}}\webapps\sampleapp) {
          Remove-Item ${{secrets.TOMCAT_PATH}}\webapps\sampleapp -Recurse -Force
          Remove-Item ${{secrets.TOMCAT_PATH}}\webapps\*.war -Force
        }
        Move-Item .\*.war ${{secrets.TOMCAT_PATH}}\webapps\
