name: demo1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide branch name'
        required: true
        default: main
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    steps: 
    - name: Build sample app
      run: |
        echo "backend_status=success" >> "$GITHUB_OUTPUT"
        echo "frontend_status=success" >> "$GITHUB_OUTPUT"
      
  test1:
    needs: [demo]
    if: needs.demo.outputs.backend_status == 'success' && needs.demo.outputs.frontend_status == 'success'
    runs-on: ubuntu-latest
    steps: 
    - name: echo success
      run: echo "succees""
      
