name: deploy

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ inputs.env_name }}

    steps:   
    - name: Deploy app
      run: |
        if (Test-Path ${{ secrets.TOMCAT_PATH_ENV }}\webapps\sampleapp) {
          Remove-Item ${{ secrets.TOMCAT_PATH_ENV }}\webapps\sampleapp -Recurse -Force
          Remove-Item ${{ secrets.TOMCAT_PATH_ENV }}\webapps\*.war -Force
        }
        Move-Item .\*.war ${{ secrets.TOMCAT_PATH_ENV }}\webapps\
